import type { Metadata } from "next";
import { Tektur } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const tektur = Tektur({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{backgroundColor: "#0c0c0c", minHeight: "100vh"}}
        className={`${tektur.className} ${tektur.className} antialiased `}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
